[package]
name = "mail-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"
mail-smtp-proto = { path = "../crates/mail-smtp-proto" }

[[bin]]
name = "smtp_command"
path = "fuzz_targets/smtp_command.rs"
test = false
doc = false
bench = false

[workspace]
