[package]
name = "mail-smtp-client"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mail-arc = { path = "../mail-arc" }
mail-dkim = { path = "../mail-dkim" }
mail-dns = { path = "../mail-dns" }
mail-storage = { path = "../mail-storage" }
rustls.workspace = true
rustls-platform-verifier.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true

[lints]
workspace = true
