[package]
name = "maild"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum-server.workspace = true
clap.workspace = true
mail-acme = { path = "../../crates/mail-acme" }
mail-admin-api = { path = "../../crates/mail-admin-api" }
mail-migrations = { path = "../../crates/mail-migrations" }
mail-imap-server = { path = "../../crates/mail-imap-server" }
mail-config = { path = "../../crates/mail-config" }
mail-postgres = { path = "../../crates/mail-postgres" }
mail-dns = { path = "../../crates/mail-dns" }
mail-smtp-server = { path = "../../crates/mail-smtp-server" }
mail-storage = { path = "../../crates/mail-storage" }
mail-tls = { path = "../../crates/mail-tls" }
rustls.workspace = true
sqlx.workspace = true
tokio.workspace = true

[lints]
workspace = true
