[package]
name = "mail-storage"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
mail-domain = { path = "../mail-domain" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
