[package]
name = "mail-postgres"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
mail-domain = { path = "../mail-domain" }
mail-dsn = { path = "../mail-dsn" }
mail-mailbox = { path = "../mail-mailbox" }
mail-migrations = { path = "../mail-migrations" }
mail-storage = { path = "../mail-storage" }
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
mail-migrations = { path = "../mail-migrations" }
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
