[package]
name = "mail-imap-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
argon2.workspace = true
base64.workspace = true
mail-imap-proto = { path = "../mail-imap-proto" }
mail-storage = { path = "../mail-storage" }
rustls.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
uuid.workspace = true

[dev-dependencies]
async-trait.workspace = true
rcgen.workspace = true

[lints]
workspace = true
